// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config';
import { defineConfig, env } from 'prisma/config';
import { posix } from 'path';

export default defineConfig({
  schema: posix.join('src', 'infra', 'database', 'prisma', 'schema.prisma'),
  migrations: {
    path: posix.join('src', 'infra', 'database', 'prisma', 'migrations'),
  },
  datasource: {
    url: env('DATABASE_URL'),
  },
});
